[package]
name = "advent-of-code-rust-2020"
version = "0.1.0"
authors = ["sonowz <dnsdhrj123@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99"
mapcomp = "0.2.2"
nom = "6.0.1"
